[versions]
kyori_version = "4.14.0"

shadow_version = "8.1.1"
paperweight_version = "1.5.9"
runpaper_version = "2.2.3"

modrinth_version = "2.8.7"
hangar_version = "0.1.2"

[plugins]
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar_version" }
modrinth = { id = "com.modrinth.minotaur", version.ref = "modrinth_version" }

paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight_version" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runpaper_version" }
shadowjar = { id = "com.github.johnrengelman.shadow", version.ref = "shadow_version" }

[libraries]
adventure = { module = "net.kyori:adventure-api", version.ref = "kyori_version" }
minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "kyori_version" }

paperweight = { module = "io.papermc.paperweight:paperweight-userdev", version.ref = "paperweight_version" }
shadowjar = { module = "com.github.johnrengelman:shadow", version.ref = "shadow_version" }
runpaper = { module = "xyz.jpenilla:run-task", version.ref = "runpaper_version" }

hangar = { module = "io.papermc:hangar-publish-plugin", version.ref = "hangar_version" }
modrinth = { module = "com.modrinth.minotaur:Minotaur", version.ref = "modrinth_version" }