name: '${name}'
main: '${group}.${name}'

authors: ${authors}

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'
website: '${website}'

softdepend: [CMI, DecentHolograms, HolographicDisplays, PlaceholderAPI, ItemsAdder, Oraxen]

commands:
  crates:
    description: The base command for Crazy Crates
    aliases: [crazycrates, crazycrate, crate, cc]
  keys:
    description: Views the amount of keys you/others have.
    aliases: [key]

permissions:
  crazycrates.command.player.help:
    default: true
    children:
      crazycrates.command.player.key: true

  crazycrates.command.player.menu:
    default: true

  crazycrates.command.player.key:
    default: op

  crazycrates.command.player.key.others:
    default: op
    children:
      crazycrates.command.player.key: true

  crazycrates.command.players.*:
    default: op
    children:
      crazycrates.command.player.key.others: true
      crazycrates.command.player.help: true
      crazycrates.command.player.menu: true

  crazycrates.command.admin.*:
    default: op
    children:
      crazycrates.command.admin.schematic.*: true
      crazycrates.command.admin.help: true
      crazycrates.command.admin.convert: true
      crazycrates.command.admin.debug: true
      crazycrates.command.admin.setmenu: true
      crazycrates.command.admin.giveall: true
      crazycrates.command.admin.forceopen: true
      crazycrates.command.admin.open.others: true
      crazycrates.command.admin.list: true
      crazycrates.command.admin.preview: true
      crazycrates.command.admin.additem: true
      crazycrates.command.admin.access: true

  crazycrates.command.admin.additem:
    default: op

  crazycrates.command.admin.access:
    default: op

  crazycrates.command.admin.preview:
    default: op

  crazycrates.command.admin.list:
    default: op
    children:
      crazycrates.command.admin.teleport: true

  crazycrates.command.admin.open:
    default: op

  crazycrates.command.admin.open.others:
    default: op
    children:
      crazycrates.command.admin.open: true

  crazycrates.command.admin.takekey:
    default: op
    children:
      crazycrates.command.player.transfer: true

  crazycrates.command.player.transfer:
    default: op

  crazycrates.command.admin.forceopen:
    default: op
    children:
      crazycrates.command.admin.open: true
      crazycrates.command.admin.open.others: true

  crazycrates.command.admin.teleport:
    default: op

  crazycrates.command.admin.givekey:
    default: op

  crazycrates.command.admin.giverandomkey:
    default: op

  crazycrates.command.admin.giveall:
    default: op
    children:
      crazycrates.command.admin.givekey: true
      crazycrates.command.admin.giverandomkey: true
      crazycrates.command.admin.takekey: true
      crazycrates.command.player.transfer: true

  crazycrates.command.admin.set:
    default: op

  crazycrates.command.admin.setmenu:
    default: op
    children:
      crazycrates.command.admin.set: true

  crazycrates.command.admin.reload:
    default: op

  crazycrates.command.admin.debug:
    default: op

  crazycrates.command.admin.convert:
    default: op

  crazycrates.command.admin.schematic.*:
    default: op
    children:
      crazycrates.command.admin.schematic.save: true
      crazycrates.command.admin.schematic.set: true

  crazycrates.command.admin.schematic.save:
    default: op

  crazycrates.command.admin.schematic.set:
    default: op

  crazycrates.command.admin.help:
    default: op
    children:
      crazycrates.command.admin.reload: true